-- CourtCheck PostgreSQL Schema
-- Run with: psql $DATABASE_URL -f schema.sql

CREATE TABLE IF NOT EXISTS courts (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  num_courts INTEGER NOT NULL,
  surface TEXT NOT NULL,
  public_private TEXT NOT NULL,
  maps_link TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reports (
  id SERIAL PRIMARY KEY,
  court_id INTEGER NOT NULL REFERENCES courts(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  comment TEXT,
  photo_paths TEXT,
  flag_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Seed data: Courts
INSERT INTO courts (name, address, city, state, num_courts, surface, public_private, maps_link) VALUES
  ('Bluemont Park', '601 N Manchester St', 'Arlington', 'VA', 9, 'hard', 'public', 'https://maps.google.com/?q=Bluemont+Park+Tennis+Arlington+VA'),
  ('Quincy Park', '1021 N Quincy St', 'Arlington', 'VA', 6, 'hard', 'public', 'https://maps.google.com/?q=Quincy+Park+Tennis+Arlington+VA'),
  ('Virginia Highlands Park', '1600 S Hayes St', 'Arlington', 'VA', 6, 'hard', 'public', 'https://maps.google.com/?q=Virginia+Highlands+Park+Tennis+Arlington+VA'),
  ('Barcroft Park', '4200 S Four Mile Run Dr', 'Arlington', 'VA', 5, 'hard', 'public', 'https://maps.google.com/?q=Barcroft+Park+Tennis+Arlington+VA'),
  ('Towers Park', '801 S Scott St', 'Arlington', 'VA', 4, 'hard', 'public', 'https://maps.google.com/?q=Towers+Park+Tennis+Arlington+VA'),
  ('Thomas Jefferson Park', '3501 2nd St S', 'Arlington', 'VA', 4, 'hard', 'public', 'https://maps.google.com/?q=Thomas+Jefferson+Park+Tennis+Arlington+VA'),
  ('Fort Scott Park', '2800 Fort Scott Dr', 'Arlington', 'VA', 3, 'hard', 'public', 'https://maps.google.com/?q=Fort+Scott+Park+Tennis+Arlington+VA'),
  ('Gunston Park', '1200 28th St S', 'Arlington', 'VA', 3, 'hard', 'public', 'https://maps.google.com/?q=Gunston+Park+Tennis+Arlington+VA'),
  ('Marcey Road Park', '2800 N Marcey Rd', 'Arlington', 'VA', 3, 'hard', 'public', 'https://maps.google.com/?q=Marcey+Road+Park+Tennis+Arlington+VA'),
  ('Glebe Road Park', '4211 N Old Glebe Rd', 'Arlington', 'VA', 3, 'hard', 'public', 'https://maps.google.com/?q=Glebe+Road+Park+Tennis+Arlington+VA'),
  ('Walter Reed Community Center', '2909 16th St S', 'Arlington', 'VA', 3, 'hard', 'public', 'https://maps.google.com/?q=Walter+Reed+Community+Center+Tennis+Arlington+VA'),
  ('Jennie Dean Park', '3630 27th St S', 'Arlington', 'VA', 3, 'hard', 'public', 'https://maps.google.com/?q=Jennie+Dean+Park+Tennis+Arlington+VA'),
  ('Carver Community Center', '1415 S Queen St', 'Arlington', 'VA', 3, 'hard', 'public', 'https://maps.google.com/?q=Carver+Community+Center+Tennis+Arlington+VA'),
  ('Lyon Village Park', '1998 N Highland St', 'Arlington', 'VA', 2, 'hard', 'public', 'https://maps.google.com/?q=Lyon+Village+Park+Tennis+Arlington+VA'),
  ('Hayes Park', '1510 N Lincoln St', 'Arlington', 'VA', 2, 'hard', 'public', 'https://maps.google.com/?q=Hayes+Park+Tennis+Arlington+VA'),
  ('Bon Air Park', '850 N Lexington St', 'Arlington', 'VA', 2, 'hard', 'public', 'https://maps.google.com/?q=Bon+Air+Park+Tennis+Arlington+VA'),
  ('Maury Park', '3558 N Wilson Blvd', 'Arlington', 'VA', 2, 'hard', 'public', 'https://maps.google.com/?q=Maury+Park+Tennis+Arlington+VA'),
  ('Tuckahoe Park', '2409 N Tuckahoe St', 'Arlington', 'VA', 2, 'hard', 'public', 'https://maps.google.com/?q=Tuckahoe+Park+Tennis+Arlington+VA'),
  ('Stratford Park', '4264 23rd St N', 'Arlington', 'VA', 2, 'hard', 'public', 'https://maps.google.com/?q=Stratford+Park+Tennis+Arlington+VA'),
  ('Madison Manor Park', '6225 12th Rd N', 'Arlington', 'VA', 2, 'hard', 'public', 'https://maps.google.com/?q=Madison+Manor+Park+Tennis+Arlington+VA'),
  ('Langston-Brown Community Center', '2121 N Culpeper St', 'Arlington', 'VA', 1, 'hard', 'public', 'https://maps.google.com/?q=Langston-Brown+Community+Center+Arlington+VA'),
  ('Four Mile Run Park', '3700 S Four Mile Run Dr', 'Arlington', 'VA', 1, 'hard', 'public', 'https://maps.google.com/?q=Four+Mile+Run+Park+Tennis+Arlington+VA'),
  ('Banneker Tennis Courts', '2500 Georgia Ave NW', 'Washington', 'DC', 8, 'hard', 'public', 'https://maps.google.com/?q=Banneker+Tennis+Courts+Washington+DC'),
  ('Takoma Rec Center', '290 Van Buren St NW', 'Washington', 'DC', 6, 'hard', 'public', 'https://maps.google.com/?q=Takoma+Recreation+Center+Tennis+Washington+DC'),
  ('Fort Stevens Park', '1327 Van Buren St NW', 'Washington', 'DC', 4, 'hard', 'public', 'https://maps.google.com/?q=Fort+Stevens+Park+Tennis+Washington+DC'),
  ('Lafayette Rec Center', '5900 33rd St NW', 'Washington', 'DC', 4, 'hard', 'public', 'https://maps.google.com/?q=Lafayette+Recreation+Center+Tennis+Washington+DC'),
  ('Palisades Community Center', '5200 Sherier Pl NW', 'Washington', 'DC', 3, 'hard', 'public', 'https://maps.google.com/?q=Palisades+Recreation+Center+Tennis+Washington+DC'),
  ('Hearst Park', '3680 Quebec St NW', 'Washington', 'DC', 3, 'hard', 'public', 'https://maps.google.com/?q=Hearst+Park+Tennis+Washington+DC'),
  ('Fort Reno Park', '4000 Chesapeake St NW', 'Washington', 'DC', 3, 'hard', 'public', 'https://maps.google.com/?q=Fort+Reno+Park+Tennis+Washington+DC'),
  ('Chevy Chase Rec Center', '5601 Connecticut Ave NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Chevy+Chase+Recreation+Center+Tennis+Washington+DC'),
  ('Forest Hills Park', '3999 Connecticut Ave NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Forest+Hills+Park+Tennis+Washington+DC'),
  ('Friendship Turtle Park', '4500 Van Ness St NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Friendship+Turtle+Park+Tennis+Washington+DC'),
  ('Georgetown Rec Center', '3350 Q St NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Georgetown+Recreation+Center+Tennis+Washington+DC'),
  ('Hardy Rec Center', '1819 35th St NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Hardy+Recreation+Center+Tennis+Washington+DC'),
  ('Powell Recreation Center', '3149 16th St NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Powell+Recreation+Center+Tennis+Washington+DC'),
  ('Raymond Playground', '900 Rock Creek Church Rd NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Raymond+Playground+Tennis+Washington+DC'),
  ('Reed Park', '2200 18th St NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Reed+Park+Tennis+Washington+DC'),
  ('Roosevelt HS Courts', '4301 13th St NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Roosevelt+High+School+Tennis+Washington+DC'),
  ('Volta Park', '3400 Q St NW', 'Washington', 'DC', 2, 'hard', 'public', 'https://maps.google.com/?q=Volta+Park+Tennis+Washington+DC'),
  ('Bruce Monroe Community Park', '3000 Georgia Ave NW', 'Washington', 'DC', 1, 'hard', 'public', 'https://maps.google.com/?q=Bruce+Monroe+Park+Tennis+Washington+DC'),
  ('Kennedy Rec Center', '1401 7th St NW', 'Washington', 'DC', 1, 'hard', 'public', 'https://maps.google.com/?q=Kennedy+Recreation+Center+Tennis+Washington+DC'),
  ('Rock Creek Tennis Center', '5500 16th St NW', 'Washington', 'DC', 25, 'hard', 'public', 'https://maps.google.com/?q=Rock+Creek+Tennis+Center+Washington+DC'),
  ('Montrose Park', '3050 R St NW', 'Washington', 'DC', 4, 'hard', 'public', 'https://maps.google.com/?q=Montrose+Park+Tennis+Washington+DC'),
  ('Francis Field', '2300 N St NW', 'Washington', 'DC', 4, 'hard', 'public', 'https://maps.google.com/?q=Francis+Field+Tennis+Washington+DC'),
  ('Rose Park', '2650 O St NW', 'Washington', 'DC', 3, 'hard', 'public', 'https://maps.google.com/?q=Rose+Park+Tennis+Washington+DC'),
  ('Park Road Courts', 'Beach Dr NW & Park Rd NW', 'Washington', 'DC', 3, 'hard', 'public', 'https://maps.google.com/?q=Park+Road+Courts+Rock+Creek+Park+Washington+DC');

-- Seed data: Sample reports
INSERT INTO reports (court_id, status, comment, created_at) VALUES
  (1, 'Closed', 'Facility closed for renovation until late 2027. Fences are up around all courts.', NOW() - INTERVAL '14 days'),
  (1, 'Great', 'Courts are in good shape but the facility is closed for renovation until late 2027.', NOW() - INTERVAL '6 hours'),
  (2, 'Great', 'Midweek morning — had courts to ourselves. Surface is solid, nets are good.', NOW() - INTERVAL '3 days'),
  (2, 'Busy/Long Wait', 'Quincy is always packed on weekends. Come early or wait 30+ min.', NOW() - INTERVAL '24 hours'),
  (3, 'Busy/Long Wait', 'Courts were full at 9am Saturday. Got on after 20 min wait.', NOW() - INTERVAL '5 days'),
  (3, 'Great', 'All 6 courts in great condition. Nets are tight, surface recently resurfaced.', NOW() - INTERVAL '45 minutes'),
  (4, 'Great', 'Nice courts, not too crowded on a Tuesday. Surface has some wear but very playable.', NOW() - INTERVAL '7 days'),
  (4, 'Great', 'Played doubles here this morning. All 5 courts open. Clean and well-maintained.', NOW() - INTERVAL '18 hours'),
  (5, 'Great', 'Courts in good shape. Got a nice breeze up on the hill.', NOW() - INTERVAL '6 days'),
  (5, 'Busy/Long Wait', 'Saturday morning — all 4 courts occupied with people waiting. 20-30 min wait.', NOW() - INTERVAL '4 hours'),
  (6, 'Cracks/Uneven', 'Court 2 has a nasty crack along the baseline. Courts 1 and 3-4 are fine.', NOW() - INTERVAL '10 days'),
  (6, 'Great', 'They patched the crack on court 2! All 4 courts are now in good shape.', NOW() - INTERVAL '90 minutes'),
  (7, 'Great', 'Hidden gem — 3 courts tucked away and rarely busy. Surface is decent.', NOW() - INTERVAL '4 days'),
  (7, 'Great', 'Played singles at 7am, had the whole place to myself. Love this spot.', NOW() - INTERVAL '2 days'),
  (8, 'Wet/Puddles', 'Rained last night, courts 1-2 still have standing water. Court 3 drains better.', NOW() - INTERVAL '3 days'),
  (8, 'Great', 'All dry now. Nets are a bit saggy on court 1 but playable.', NOW() - INTERVAL '20 hours'),
  (9, 'Great', 'Quiet courts in a nice wooded area. All 3 in good condition.', NOW() - INTERVAL '8 days'),
  (9, 'Busy/Long Wait', 'Surprisingly busy for a Wednesday evening. All 3 courts taken.', NOW() - INTERVAL '2 days'),
  (10, 'Great', 'Clean courts, recently resurfaced. Lines are crisp and bright.', NOW() - INTERVAL '5 days'),
  (10, 'Great', 'Still looking great. Played for 2 hours with no wait.', NOW() - INTERVAL '30 minutes'),
  (11, 'Cracks/Uneven', 'Some cracks forming near the net on court 2. Still playable but watch your step.', NOW() - INTERVAL '12 days'),
  (11, 'Great', 'Courts 1 and 3 are fine. Court 2 cracks are minor — no issue for casual play.', NOW() - INTERVAL '3 days'),
  (12, 'Great', 'Brand new courts at the renovated park! Surface is pristine.', NOW() - INTERVAL '6 days'),
  (12, 'Busy/Long Wait', 'New courts are popular — expect a wait on weekends. Weekday mornings are open.', NOW() - INTERVAL '1 day'),
  (13, 'Great', 'Good courts, well-lit for evening play. Surface is standard hard court.', NOW() - INTERVAL '9 days'),
  (13, 'Great', 'Played under the lights last night. Courts were empty after 8pm.', NOW() - INTERVAL '4 days'),
  (14, 'Great', 'Two courts in a cute neighborhood park. Both in good shape.', NOW() - INTERVAL '7 days'),
  (14, 'Wet/Puddles', 'Morning dew still on the courts at 7am. Dry by 9.', NOW() - INTERVAL '2 days'),
  (15, 'Great', 'Solid courts. Nothing fancy but clean and well-maintained.', NOW() - INTERVAL '11 days'),
  (15, 'Great', 'Stopped by after work. One court free, played for an hour. Good condition.', NOW() - INTERVAL '5 days'),
  (16, 'Great', 'Nice spot near the rose garden. Courts are in good condition.', NOW() - INTERVAL '8 days'),
  (16, 'Cracks/Uneven', 'Small crack developing on court 1 near the service line. Court 2 is perfect.', NOW() - INTERVAL '90 minutes'),
  (17, 'Great', 'Both courts in good shape. Some leaves on the court but easy to sweep.', NOW() - INTERVAL '6 days'),
  (17, 'Great', 'Played doubles this evening. Courts are well-maintained. Love this park.', NOW() - INTERVAL '3 days'),
  (18, 'Great', 'Courts are clean and lines are visible. Quiet residential area.', NOW() - INTERVAL '10 days'),
  (18, 'Great', 'Both courts open on a Saturday morning! Surface is good. Nets tight.', NOW() - INTERVAL '4 days'),
  (19, 'Wet/Puddles', 'Court 1 has a low spot that collects water. Court 2 drains fine.', NOW() - INTERVAL '7 days'),
  (19, 'Great', 'Both courts dry and playable. Nice quiet park for tennis.', NOW() - INTERVAL '2 days'),
  (20, 'Great', 'Two courts in a nice residential area. Well-maintained and rarely crowded.', NOW() - INTERVAL '9 days'),
  (20, 'Great', 'Played here after work. Had both courts to ourselves. Great surface.', NOW() - INTERVAL '5 days'),
  (21, 'Great', 'Single court but it''s in great shape. Perfect for a quick hit.', NOW() - INTERVAL '12 days'),
  (21, 'Busy/Long Wait', 'Only one court so if anyone is there you''re waiting. Came back in an hour.', NOW() - INTERVAL '6 days'),
  (22, 'Cracks/Uneven', 'Surface is rough — several cracks and some moss growing near the baseline.', NOW() - INTERVAL '15 days'),
  (22, 'Cracks/Uneven', 'Still in rough shape. Playable but not great. Bring outdoor shoes.', NOW() - INTERVAL '3 days'),
  (23, 'Busy/Long Wait', 'Saturday afternoon — packed as usual. Great facility though.', NOW() - INTERVAL '5 days'),
  (23, 'Great', 'All 8 lighted courts in excellent shape. Best public courts in NW DC.', NOW() - INTERVAL '1 hour'),
  (24, 'Great', 'Six solid courts. Surface was just cleaned. Parking lot right there.', NOW() - INTERVAL '8 days'),
  (24, 'Great', 'Played doubles on courts 3-4. Good condition, nets properly tensioned.', NOW() - INTERVAL '2 days'),
  (25, 'Great', 'All 4 courts available on a weekday. Surface is clean and well-maintained.', NOW() - INTERVAL '6 days'),
  (25, 'Wet/Puddles', 'Rain earlier today left puddles on courts 1-2. Courts 3-4 are playable.', NOW() - INTERVAL '1 day'),
  (26, 'Great', 'Nice facility with 4 courts. Clean bathrooms nearby. Nets are tight.', NOW() - INTERVAL '5 days'),
  (26, 'Busy/Long Wait', 'Weekend league was using 3 courts. One available but had to wait 15 min.', NOW() - INTERVAL '1 day'),
  (27, 'Great', 'Three courts in a lovely neighborhood. All in great shape.', NOW() - INTERVAL '7 days'),
  (27, 'Great', 'Came for an evening session. Courts were empty and in perfect condition.', NOW() - INTERVAL '3 days'),
  (28, 'Great', 'All 3 courts clean and ready to play. Nice park setting.', NOW() - INTERVAL '9 days'),
  (28, 'Great', 'Surface is smooth, lines freshly painted. One of the better DC parks.', NOW() - INTERVAL '4 days'),
  (29, 'Great', 'High point in DC — great breeze. Courts are in solid condition.', NOW() - INTERVAL '11 days'),
  (29, 'Cracks/Uneven', 'Court 3 has some uneven spots near the net. Courts 1-2 are fine.', NOW() - INTERVAL '5 days'),
  (30, 'Great', 'Both courts in excellent shape. Popular with the neighborhood crowd.', NOW() - INTERVAL '4 days'),
  (30, 'Busy/Long Wait', 'Waited 25 minutes on a Sunday morning. Very popular spot.', NOW() - INTERVAL '75 minutes'),
  (31, 'Great', 'Two courts in a beautiful setting. Surface is well-maintained.', NOW() - INTERVAL '8 days'),
  (31, 'Great', 'Played at sunset — gorgeous. Courts are in great shape.', NOW() - INTERVAL '2 days'),
  (32, 'Great', 'Fun park with good courts. Kids playground nearby keeps the family happy.', NOW() - INTERVAL '6 days'),
  (32, 'Great', 'Both courts open and clean. Nice surface, no complaints.', NOW() - INTERVAL '1 day'),
  (33, 'Busy/Long Wait', 'Georgetown courts are always busy. Weekday mornings are your best bet.', NOW() - INTERVAL '5 days'),
  (33, 'Great', 'Got lucky — both courts empty at 7am Tuesday. Surface is solid.', NOW() - INTERVAL '2 days'),
  (34, 'Great', 'Two courts right in Georgetown. Well-maintained, nice setting.', NOW() - INTERVAL '10 days'),
  (34, 'Great', 'Courts in good shape. A bit noisy with traffic but that''s Georgetown.', NOW() - INTERVAL '4 days'),
  (35, 'Great', 'Two courts in good condition. Neighborhood regulars are friendly.', NOW() - INTERVAL '7 days'),
  (35, 'Wet/Puddles', 'Heavy rain last night. Court 1 draining slowly. Court 2 is OK.', NOW() - INTERVAL '2 days'),
  (36, 'Great', 'Courts are clean and well-lined. Nice spot in the Rock Creek Church area.', NOW() - INTERVAL '9 days'),
  (36, 'Great', 'Played for 2 hours midday. Both courts available the whole time.', NOW() - INTERVAL '3 days'),
  (37, 'Great', 'Compact courts in Adams Morgan. Surface is decent, some wear but playable.', NOW() - INTERVAL '6 days'),
  (37, 'Busy/Long Wait', 'Evening crowd fills up fast. Waited 20 min but worth it.', NOW() - INTERVAL '1 day'),
  (38, 'Great', 'School courts open to public on weekends. Surface is OK — typical school courts.', NOW() - INTERVAL '8 days'),
  (38, 'Great', 'Played Saturday AM. Courts open and in decent shape. Bring your own net tension.', NOW() - INTERVAL '3 days'),
  (39, 'Great', 'Two courts in a charming Georgetown park. Well-kept grounds.', NOW() - INTERVAL '5 days'),
  (39, 'Great', 'Sunday morning session. Both courts clean, nets good. Love this spot.', NOW() - INTERVAL '1 day'),
  (40, 'Great', 'Single court but it''s in great condition. Quick pickup games happen here often.', NOW() - INTERVAL '10 days'),
  (40, 'Busy/Long Wait', 'Only one court — if someone is there, you wait. Try early mornings.', NOW() - INTERVAL '4 days'),
  (41, 'Cracks/Uneven', 'Court surface is aging. Some cracks near the baseline but still usable.', NOW() - INTERVAL '12 days'),
  (41, 'Great', 'They did some patching! Court looks much better now. Still just one court.', NOW() - INTERVAL '2 days'),
  (42, 'Great', 'The crown jewel — 25 courts in excellent condition. Pro shop and lessons available.', NOW() - INTERVAL '3 days'),
  (42, 'Great', 'Played on courts 10-11. Freshly resurfaced. Best public courts in the area.', NOW() - INTERVAL '50 minutes'),
  (43, 'Great', 'All 4 courts available midweek. Beautiful setting next to Dumbarton Oaks.', NOW() - INTERVAL '5 days'),
  (43, 'Great', 'Courts freshly rolled. Hard courts in solid condition. Reservations recommended.', NOW() - INTERVAL '3 hours'),
  (44, 'Great', 'Four courts right in Foggy Bottom. Great for GW students and locals.', NOW() - INTERVAL '7 days'),
  (44, 'Busy/Long Wait', 'Lunch hour rush — all 4 courts full with a wait. Try before 11am.', NOW() - INTERVAL '2 days'),
  (45, 'Great', 'Three courts in a classic Georgetown park. Surface is good.', NOW() - INTERVAL '6 days'),
  (45, 'Wet/Puddles', 'Courts 2 and 3 still have puddles from last night''s rain. Court 1 is playable.', NOW() - INTERVAL '8 hours'),
  (46, 'Wet/Puddles', 'Shaded by trees so they stay wet longer after rain. Court 1 was dry.', NOW() - INTERVAL '5 days'),
  (46, 'Great', 'Beautiful park, courts are in good shape. Nets could be tighter.', NOW() - INTERVAL '12 hours');
